### ISSUE TITLE
Uno vs Nano

### ISSUE THREAD

**Issue by Kegzie73** [jg-storey/flight-panels-ded#1]
Hi mate,

Great work, got it all up and running no probs at all on the UNO. Both F16 & F18 working beautiful. 

When I upload the code to a Nano I get a different story, code compiles and uploads fines, when it runs the screen blinks and goes blank. Tried a few different boards and the same result. 

I am using the old bootloader on the Nanos and the wiring guide as posted on the old DED thread. Any tips on what might be the issue?Trying to tuck this away in a box and the UNO is abit large.

Once again, awesome work its helped me a lot inflight especially with GPS Co-ords, I don't have to look away from the Stream deck as I've got it stuck on top :)

Cheers

Pat

**Comment by jg-storey** [comment]
@Kegzie73 Glad you've managed to get it working with the UNO. I'm not sure why it wouldn't work with your Nano. Mine works fine. Presumably it's wired up correctly. I always use Nanos with the original FTDI FT232RL chip. Cheaper clones tend to have the CH340. I don't know if that matters or not.
Have you tried to run a simple program on the Nano to check that it is working properly first? Something like this perhaps https://arduinogetstarted.com/tutorials/arduino-hello-world

Regards,
James.

**Comment by Kegzie73** [comment]
Picked up a Nano with the FTDI FT232RL chip, uploaded the code and it worked a treat! Looks like there's an issue with the CH340 & Old Bootloader. Good learnings, might check and see if you can update the bootloader on the CH340 Nanos and see if that makes a difference, as I've got quite a few of them and it explains a few issue s I've had with the. Thanks again and great work keep it up!

**Comment by Kegzie73** [comment]
Cheers again, here's the result.
![Uploading IMG_0187_Comment.jpg…]()

**Comment by jg-storey** [comment]
@Kegzie73 Fantastic. Glad you were able to get it working. Happy flying!
