### ISSUE TITLE
F16 DED 

### ISSUE THREAD

**Issue by Kegzie73** [jg-storey/flight-panels-ded#2]
Hi mate,

Hope your doing well. Just reaching out for some help, I've been getting back into the F16 and noticed with the recent DCS updates the DED isn't working all that well. It just displays some characters on the left of the panel. The F18 still works a treat and couldn't do without it now :) I know there's been a fair bit of work by ED on the F16 module of recent so maybe something has changed, was hoping you could give me some advice on this.

I've updated to the latest DCS-BIOS  etc also and get the same.

Cheers

Pat
![IMG_0337](https://github.com/jg-storey/flight-panels-ded/assets/146910690/af65c41a-ebcf-4dad-8257-ae6e61353ad7)

**Comment by Kegzie73** [comment]
Hi,

Some more detail, looks like DCS-BIOS is working ok as its sending the right values/string (see pic). Must be something to do with the formatting of the string in the code?

![ded](https://github.com/jg-storey/flight-panels-ded/assets/146910690/cccdc576-307f-4c09-bdce-25b0d9867638)

Cheers

Pat

**Comment by Kegzie73** [comment]
Hi.

All sorted, I had the old code which used different addresses for the F16 DED. Updated with the newer version 1.22 and all good! Sorry to bother you.

Cheers

Pat

**Comment by jg-storey** [comment]
@Kegzie73 Glad you were able to sort it.
James
